services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - blog
      - russiankisa
    restart: unless-stopped
    networks:
      - app-network

  blog:
    build:
      context: ./blog
      dockerfile: Dockerfile
    container_name: blog-app
    environment:
      - NODE_ENV=production
    env_file:
      - ./blog/.env
    restart: unless-stopped
    networks:
      - app-network

  russiankisa:
    build:
      context: ./russiankisa
      dockerfile: Dockerfile
    container_name: russiankisa-app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 